version: '3.7'
services:
  mongodb_contenedor:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=chaacDB
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  chaac_client:
    container_name: chaac_client
    image: fbalderasd/python:3.7-sb 
    volumes:
      - ./app:/home/:rw \
    ports:
      - 45000:45000
    restart: always
    networks:
      - chaac